spring:
  application:
    name: 'finsavior-config-server'
  cloud:
    config:
      name: '${spring.application.name}'
      server:
        bootstrap: true
        git:
          skipSslValidation: true
          uri: https://github.com/Hachibitz/finsavior-cloud-properties.git
          username:  ${TOKEN}
          password:  ${TOKEN}
          basedir: '${user.home}/${spring.application.name}/default'
          force-pull: true
          clone-on-start: true

server:
  port: 8084